version: '3.8'

services:
  web:
    image: w3ll1n9t0n/app:v8
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_PASSWORD: Senha123
      MYSQL_DB: meubanco
    networks:
      - my_network

  mysql:
    image: w3ll1n9t0n/mysql:v8
    environment:
      MYSQL_PASSWORD: Senha123
      MYSQL_DB: meubanco
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:

volumes:
  mysql_data:
