name: Build and Push Docker Images

# Dispara o workflow quando houver push ou pull request no ramo main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Construir e empurrar a imagem do aplicativo
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push app Docker image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # variável de ambiente para seu nome de usuário do Docker Hub
        password: ${{ secrets.DOCKER_PASSWORD }} # variável de ambiente para sua senha do Docker Hub
        repository: w3ll1n9t0n/app:v8 # substitua pelo nome do seu repositório do Docker Hub
        tag_with_ref: true
        push: true
        path: ./app # caminho para o diretório do seu aplicativo

    # Passo 2: Construir e empurrar a imagem do MySQL
    - name: Build and push MySQL Docker image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # variável de ambiente para seu nome de usuário do Docker Hub
        password: ${{ secrets.DOCKER_PASSWORD }} # variável de ambiente para sua senha do Docker Hub
        repository: w3ll1n9t0n/mysql:v8 # substitua pelo nome do seu repositório do Docker Hub
        tag_with_ref: true
        push: true
        path: ./mysql # caminho para o diretório do seu contêiner MySQL
