name: Build and Push Docker Images

# Dispara o workflow quando houver push ou pull request no ramo main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código-fonte
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
<<<<<<< HEAD
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Passo 3: Build e push da imagem Docker
      - name: Build and push app Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app:v8

      # Passo 2: Construir e empurrar a imagem do MySQL
      - name: Checkout code
        uses: actions/checkout@v2

        - name: Build and push app Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./mysql
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mysql:v8






=======
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Passo 3: Build e push da imagem Docker
      - name: Build and push app Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app:v8
>>>>>>> 20dbf31b52c9a0546afdeeda5b3c9808ee23ed48
